### ISSUE TITLE
出现报错thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "capture failed"', src\common\mod.rs:69:55

### ISSUE THREAD

**Issue by asd1207658704** [wormtql/yas#117]
![`Y}@0O)CG CNBQWB4U0DWDI](https://user-images.githubusercontent.com/53552777/231494806-274e077f-7937-49fe-a0f4-480d35371f4b.png)

**Comment by wormtql** [comment]
下载本地版

**Comment by asd1207658704** [comment]
本地exe运行命令行里也报同样的错误，刚刚被我删掉了。我重新下载一个，速度有些慢

**Comment by DeSireFire** [comment]
```text
[2023-04-16T15:23:17Z INFO  yas::common::utils::windows] `Shcore.dll` found
[2023-04-16T15:23:18Z INFO  yas] left = -2240, top = 197, width = 1920, height = 1080
[2023-04-16T15:23:18Z INFO  tract_linalg::x86_64_fma] mmm_f32, sigmoid_f32, tanh_f32: x86_64/fma activated
[2023-04-16T15:23:18Z INFO  tract_linalg::x86_64_fma] mmm_i8_i8 and mmm_i8_i32: x86_64/avx2 activated
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "capture failed"', src\common\mod.rs:69:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
也有的类似的问题。
系统环境是win11
下载的是地址的：
https://github.com/wormtql/yas/releases/download/v0.1.13/yas_v0.1.13.exe

启动以后，并没有操作鼠标点选圣遗物。
因为这个是单文件exe，没有配置文件产生,我也不知道RUST_BACKTRACE=1这个变量咋设置。

测试了旧版本v0.1.1.1,能控制鼠标点选圣遗物，只是会报错，总体来说不算影响使用。

**Comment by wormtql** [comment]
移步#134
