### ISSUE TITLE
识别无法启动

### ISSUE THREAD

**Issue by bayeswhu** [wormtql/yas#120]
0.11版可以正常扫描识别，0.13版启动后进入圣遗物页面，但是鼠标不移动，也不开始扫描识别
终端窗口报错如下：
[2023-04-14T14:47:11Z INFO  yas::common::utils::windows] `Shcore.dll` found
[2023-04-14T14:47:12Z INFO  yas] left = 0, top = 0, width = 3840, height = 2160
[2023-04-14T14:47:12Z INFO  tract_linalg::x86_64_fma] mmm_f32, sigmoid_f32, tanh_f32: x86_64/fma activated
[2023-04-14T14:47:12Z INFO  tract_linalg::x86_64_fma] mmm_i8_i8 and mmm_i8_i32: x86_64/avx2 activated
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "capture failed"', src\common\mod.rs:69:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Amenomori** [comment]
As the error info hints, backtrace is helpful when dealing problems like this.

You may reproduce the problem with  RUST_BACKTRACE=1 environment variable, and paste it to here. It will help locating the problem.

**Comment by bayeswhu** [comment]
Thank you.
But how to run with RUST_BACKTRACE=1? Set parameter in command line? I run it in windows with double click, could I set parameters in shortcut?
Another question is, after I set RUST_BACKTRACE=1, where could I find the backtrace, in standard output or a log file somewhere?

**Comment by solacens** [comment]
Running with console with given env var will result in a new prompt of same error but still without any trace message.

**Comment by tautomer** [comment]
full backtrace好像也没啥用

```text
[2023-06-10T05:15:18Z INFO  yas::common::utils::windows] `Shcore.dll` found
[2023-06-10T05:15:19Z INFO  yas] left = 2560, top = 0, width = 3440, height = 1440
[2023-06-10T05:15:19Z INFO  tract_linalg::x86_64_fma] mmm_f32, sigmoid_f32, tanh_f32: x86_64/fma activated
[2023-06-10T05:15:19Z INFO  tract_linalg::x86_64_fma] mmm_i8_i8 and mmm_i8_i32: x86_64/avx2 activated
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "capture failed"', src\common\mod.rs:69:55
stack backtrace:
   0:     0x7ff6314118e4 - <unknown>
   1:     0x7ff6312a121b - <unknown>
   2:     0x7ff6313ff581 - <unknown>
   3:     0x7ff63141318b - <unknown>
   4:     0x7ff631412d67 - <unknown>
   5:     0x7ff631413ae7 - <unknown>
   6:     0x7ff631413586 - <unknown>
   7:     0x7ff6314134cf - <unknown>
   8:     0x7ff6314134a4 - <unknown>
   9:     0x7ff631bf6d85 - <unknown>
  10:     0x7ff631bf7226 - <unknown>
  11:     0x7ff631bc27dd - <unknown>
  12:     0x7ff631bd6615 - <unknown>
  13:     0x7ff631246e51 - <unknown>
  14:     0x7ff631bed536 - <unknown>
  15:     0x7ff63124c590 - <unknown>
  16:     0x7ff631bf467c - <unknown>
  17:     0x7ffff62526ad - BaseThreadInitThunk
  18:     0x7ffff73aa9f8 - RtlUserThreadStart
```

**Comment by wormtql** [comment]
移步#134
