### ISSUE TITLE
最新版yas运行弹窗秒关

### ISSUE THREAD

**Issue by Kokomiooooo** [wormtql/yas#199]
按下回车直接询问管理员权限，之后有一个弹窗，接着就无事发生了

**Comment by smsra** [comment]
分辨率问题？调整为16:9

**Comment by AgMonk** [comment]
遇到相同问题，调整分辨率后已解决。帮补充一下问题描述：

版本为： v0.1.19

以管理员权限运行cmd.exe，执行yas命令后获得如下报错：

> 0x7ffbf7b50000
Some(0x7ffbf7b88c70)
thread 'main' panicked at yas\src\game_info\os\winodws.rs:79:79:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

按照提示设置环境变量之后，又提示设置环境变量为 full，修改之后获得如下报错：

>0x7ffbf7b50000
Some(0x7ffbf7b88c70)
thread 'main' panicked at yas\src\game_info\os\winodws.rs:79:79:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff64da36293 - <unknown>
   1:     0x7ff64d96c5ca - <unknown>
   2:     0x7ff64da27b47 - <unknown>
   3:     0x7ff64da376f5 - <unknown>
   4:     0x7ff64da3752d - <unknown>
   5:     0x7ff64da37b53 - <unknown>
   6:     0x7ff64da377a2 - <unknown>
   7:     0x7ff64da3772f - <unknown>
   8:     0x7ff64da3771e - <unknown>
   9:     0x7ff64e4ad251 - <unknown>
  10:     0x7ff64e4ad30d - <unknown>
  11:     0x7ff64e4ad6ae - <unknown>
  12:     0x7ff64da85164 - <unknown>
  13:     0x7ff64da3da18 - <unknown>
  14:     0x7ff64d901006 - <unknown>
  15:     0x7ff64da3b080 - <unknown>
  16:     0x7ff64e487d4c - <unknown>
  17:     0x7ffbf7a87374 - BaseThreadInitThunk
  18:     0x7ffbf8d1cc91 - RtlUserThreadStart



看到本条Issue修改分辨率为1600*900后正常运行
