### ISSUE TITLE
HDR导致识别失败

### ISSUE THREAD

**Issue by tautomer** [wormtql/yas#44]
关了HDR就好了

开启HDR的时候，yas的截图是这样的
![test](https://user-images.githubusercontent.com/15900605/160515685-c0c51ba9-287f-4484-9a2d-cb27ba6227f0.png)
看起来像是画面曝光和饱和度跟训练的差别太大吧

full backtrace，不过估计没啥用。。
```
>.\yas_v0.1.7.exe --verbose
[2022-03-29T01:38:06Z INFO  yas] Windows version >= 8.1
[2022-03-29T01:38:07Z INFO  yas] detected left: 3000
[2022-03-29T01:38:07Z INFO  yas] detected top: 32
[2022-03-29T01:38:07Z INFO  yas] detected width: 2560
[2022-03-29T01:38:07Z INFO  yas] detected height: 1440
[2022-03-29T01:38:07Z INFO  tract_linalg::x86_64_fma] mmm_f32, sigmoid_f32, tanh_f32: x86_64/fma activated
[2022-03-29T01:38:07Z INFO  tract_linalg::x86_64_fma] mmm_i8_i8 and mmm_i8_i32: x86_64/avx2 activated
[2022-03-29T01:38:07Z INFO  yas::common] capture raw time: 10ms
[2022-03-29T01:38:07Z INFO  yas::common] preprocess time: 12ms
[2022-03-29T01:38:07Z INFO  yas::scanner::yas_scanner] raw count string: 圣遗物 1393/1500
[2022-03-29T01:38:07Z INFO  yas::scanner::yas_scanner] detected count: 1393
[2022-03-29T01:38:07Z INFO  yas::scanner::yas_scanner] total row: 175
[2022-03-29T01:38:07Z INFO  yas::scanner::yas_scanner] last column: 1
[2022-03-29T01:38:08Z INFO  yas::scanner::yas_scanner] YasScanResult { name: "明威之镡", main_stat_name: "生命值", main_stat_value: "4,780", sub_stat_1: "
攻击力+29", sub_stat_2: "暴击率+3.5%", sub_stat_3: "元素充能效率+9.1%", sub_stat_4: "攻击力+18.1%", level: "+20", equip: "香菱已装备", star: 5 }
[2022-03-29T01:38:08Z INFO  yas::scanner::yas_scanner] YasScanResult { name: "明威之镡", main_stat_name: "生命值", main_stat_value: "4,780", sub_stat_1: "
防御力+19.7%", sub_stat_2: "元素充能效率+11.0%", sub_stat_3: "防御力+16", sub_stat_4: "攻击力+14.0%", level: "+20", equip: "北斗已装备", star: 5 }
thread '<unnamed>' panicked at 'index out of bounds: the len is 14212 but the index is 4294966922', src\inference\pre_process.rs:50:21
stack backtrace:
   0:     0x7ff6c3c4d73f - <unknown>
   1:     0x7ff6c3c67c2a - <unknown>
   2:     0x7ff6c3c48648 - <unknown>
   3:     0x7ff6c3c5029b - <unknown>
   4:     0x7ff6c3c4fd94 - <unknown>
   5:     0x7ff6c3c5079c - <unknown>
   6:     0x7ff6c3c5065b - <unknown>
   7:     0x7ff6c3c4e087 - <unknown>
   8:     0x7ff6c3c50359 - <unknown>
   9:     0x7ff6c3c866a0 - <unknown>
  10:     0x7ff6c3c86667 - <unknown>
  11:     0x7ff6c337824b - <unknown>
  12:     0x7ff6c3378c4f - <unknown>
  13:     0x7ff6c337c743 - <unknown>
  14:     0x7ff6c337fa27 - <unknown>
  15:     0x7ff6c339d2a9 - <unknown>
  16:     0x7ff6c3c5467c - <unknown>
  17:     0x7ffc214c54e0 - BaseThreadInitThunk
  18:     0x7ffc2322485b - RtlUserThreadStart
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src\scanner\yas_scanner.rs:583:52
stack backtrace:
   0:     0x7ff6c3c4d73f - <unknown>
   1:     0x7ff6c3c67c2a - <unknown>
   2:     0x7ff6c3c48648 - <unknown>
   3:     0x7ff6c3c5029b - <unknown>
   4:     0x7ff6c3c4fd94 - <unknown>
   5:     0x7ff6c3c5079c - <unknown>
   6:     0x7ff6c3c5065b - <unknown>
   7:     0x7ff6c3c4e087 - <unknown>
   8:     0x7ff6c3c50359 - <unknown>
   9:     0x7ff6c3c866a0 - <unknown>
  10:     0x7ff6c3c867b3 - <unknown>
  11:     0x7ff6c3370df0 - <unknown>
  12:     0x7ff6c3355e78 - <unknown>
  13:     0x7ff6c335d5b6 - <unknown>
  14:     0x7ff6c3351a9c - <unknown>
  15:     0x7ff6c3c4cfff - <unknown>
  16:     0x7ff6c3359587 - <unknown>
  17:     0x7ff6c3c733d4 - <unknown>
  18:     0x7ffc214c54e0 - BaseThreadInitThunk
  19:     0x7ffc2322485b - RtlUserThreadStart
```

**Comment by poly000** [comment]
找了一下似乎没有windows api可以关闭HDR
启动显示设置让用户自己关闭？

**Comment by leverule** [comment]
同样HDR下失败，但关了HDR发现识别好多出错了
<img width="789" alt="image" src="https://user-images.githubusercontent.com/57491211/221194054-b7f8738b-a9ba-4ed2-8d9c-9117dc68e44a.png">
爆伤800。。

**Comment by leverule** [comment]
删掉旧结果，关HDR-重启原神-改成1080p窗口模式就好了

**Comment by wormtql** [comment]
移步#177
